[package]
name = "echo-carve-native"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"
repository = "https://github.com/markup-carve/echo-carve"
homepage = "https://markup-carve.github.io/carve/"

[lib]
name = "carve_ffi"
crate-type = ["cdylib"]

[dependencies]
carve-lang = { git = "https://github.com/markup-carve/carve-rs.git", rev = "fd79f056f11b3f2a8472c8756146e2e98331a665", default-features = false }

[profile.release]
lto = "thin"
codegen-units = 1
