[package]
name = "carve-echo-native"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "carve_ffi"
crate-type = ["cdylib"]

[dependencies]
carve-lang = { git = "https://github.com/markup-carve/carve-rs.git", rev = "d512479051a72a045581e2c289d6b6c7555ee1e1", default-features = false }

[profile.release]
lto = "thin"
codegen-units = 1
